### ISSUE TITLE
Nested DB transactions of cascading parent, child, grandchild and great grandchild?

### ISSUE THREAD

**Issue by iamjrock** [shiftonelabs/laravel-cascade-deletes#11]
I can see that the DB transaction must fire multiple times as each `static::deleting` event is called down the cascading chain.

Does this result in nested DB transactions?  Or does Laravel merge them into a *single* DB transaction covering deletion of parent, child, grandchild and great grandchild?

Just trying to understand how that works please.

**Comment by patrickcarlohickman** [comment]
@iamjrock 

Yes, this does result in nested transactions, but the implementation of nested transactions is DB specific. Some databases don't support nested transactions, but do support savepoints within transactions (mysql, postges, sqlite).

That said, if an exception occurs when deleting a child, grandchild, etc., that exception is not caught, and will end up bubbling up to the original parent transaction, which will be rolled back. This allows for an "all or none" operation, where if any delete fails at any level, nothing is actually deleted.

**Comment by iamjrock** [comment]
Got it thx!
