### ISSUE TITLE
Bug delete user model

### ISSUE THREAD

**Issue by quevlu** [shiftonelabs/laravel-cascade-deletes#2]
Hi, I have an error when I try to delete the user model with their relationships.

[App\Models\v1\User\User]: error occurred deleting [qualifications]. Only deleted [0] out of [7] records.

Mu user model

`<?php

namespace App\Models\v1\User;

use App\Models\v1\Activity\Activity;
use App\Models\v1\Base;
use App\Models\v1\Qualification\Qualification;
use App\Models\v1\Report\Report;
use Illuminate\Database\Eloquent\SoftDeletes;
use ShiftOneLabs\LaravelCascadeDeletes\CascadesDeletes;

class User extends Base
{
    use SoftDeletes, CascadesDeletes;

    protected $table = 'user';
    protected $fillable = [
        'email',
        'password',
        'user_role_id'
    ];
    protected $hidden = [
        'password',
        'id'
    ];

    protected $cascadeDeletes = [
        'profile',
        'reports',
        'qualifications',
        'activities'
    ];`

**Comment by patrickcarlohickman** [comment]
What version of Laravel are you on (please look in your `composer.lock` file to find the exact version of `laravel/framework` being used)?

Can you show the `qualifications` relationship on the `User` model?

Can you show the `Qualification` model?

Thanks,
Patrick

**Comment by quevlu** [comment]
Hello Patrick, I'm using lumen version 7.0.

Qualifications relationship in the user model

```
public function qualifications()
    {
        return $this->hasMany(Qualification::class, 'user_id');
    }
```

Relationship in qualification model to user model
```
public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
```

**Comment by patrickcarlohickman** [comment]
Does your `Qualification` model also use soft deletes?

**Comment by quevlu** [comment]
@patrickcarlohickman. Yes My model qualification use soft deletes

**Comment by patrickcarlohickman** [comment]
Yeah, looks like they changed how the `exists` property works for soft deleted records in Laravel 5.5. When this package was originally created, Laravel was only at 5.3.

I'm working on an update. I'll let you know when it's available.

**Comment by quevlu** [comment]
Awesome, Very thank for your work. I will be waiting for your answer. Thanks!

**Comment by patrickcarlohickman** [comment]
@byinff A new release has been tagged (1.0.1). This should resolve the issue for you.

I'll leave this open until you confirm it's solved your issue.

Thanks,
Patrick

**Comment by quevlu** [comment]
@patrickcarlohickman Hi man, sorry for my delay. This works perfectly. Excellent work. Thank you so much
