### ISSUE TITLE
i got this when try delete data on parent using tinker

### ISSUE THREAD

**Issue by subhanassiddik** [shiftonelabs/laravel-cascade-deletes#5]
LogicException with message '[App/User]: invalid relationship(s) for cascading deletes. Relationship method(s) [Company] must return an object of type Illuminate/Database/Eloquent/Relations/Relation.'

**Comment by patrickcarlohickman** [comment]
That means that the `Company` method on your `User` model does not return a relationship. What does your `Company` method look like?

**Comment by subhanassiddik** [comment]
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use ShiftOneLabs\LaravelCascadeDeletes\CascadesDeletes;

class Company extends Model
{
    // use Notifiable;
    use CascadesDeletes;

    protected $cascadeDeletes = ['users'];

    protected $fillable = [
        'name', 'address','phone'
    ];

    public function users()
    {
        return $this->morphMany(User::class,'userable');
    }
}`

**Comment by patrickcarlohickman** [comment]
@subhanassiddik That's your `Company` model. I was looking for the `Company()` method you have defined on your `User` model.

Cascading deletes only works with relationships. The relationship methods you specify in your `$cascadeDeletes` property must return relation query objects.

**Comment by subhanassiddik** [comment]
```
<?php

namespace App;

use ShiftOneLabs\LaravelCascadeDeletes\CascadesDeletes;

use App\Role;

class User extends Authenticatable
{
    use CascadesDeletes;
    protected $cascadeDeletes = ['userable'];
   
 public function userable()
    {
        return $this->morphTo();
    }   
}



```
I don't have a method company cause I'm used polymorphic relations.

**Comment by patrickcarlohickman** [comment]
Based on the code you posted, are you still getting this error? The error message you've shown specifies that in your `App\User` model, you had specified `'Company'` in your `$cascadeDeletes` array, however the code you posted does not show that.

**Comment by patrickcarlohickman** [comment]
@subhanassiddik ,

Another issue I see with the code that you've shown is that you're attempting to cascade delete on a `MorphTo` relationship. This would throw an exception stating "[App\User]: error occurred deleting [userable]. Relation type [Illuminate\Database\Eloquent\Relations\MorphTo] not handled."

From the documentation (specifies BelongsTo, but MorphTo is basically the same and extends BelongsTo):

> Do not add a BelongsTo relationship to the $cascadeDeletes array. This will cause a LogicException, and no records will be deleted. This is done as a BelongsTo typically represents a child record, and it usually does not make sense to delete a parent record from a child record.
